// <auto-generated />
namespace AspNet_RssReader_Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Makesourceindexnotunique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Makesourceindexnotunique));
        
        string IMigrationMetadata.Id
        {
            get { return "201612101908043_Make source index not unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
