// <auto-generated />
namespace AspNet_RssReader_Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addarticleauthor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addarticleauthor));
        
        string IMigrationMetadata.Id
        {
            get { return "201612051117038_Add article author"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
